module.exports = {
  starterbot: require("./players/starterbot"),
  // random: require("./players/randombot"),
  // beasty: require("./players/beasty"),
  myTeamBot: require("./players/team19Bot")
  DanceDanceRevolution: require("./players/DanceDanceRevolution"),
  random: require('./players/randombot'),
  rumba: require("./players/rumba"),
  shootermcgavin: require('./players/shootermcgavin'),
  awesomebot: require('./players/awesomebot'),
  // beasty: require("./players/beasty"),
  starterbot: require("./players/starterbot"),
  random: require("./players/randombot"),
  team7: require("./players/team7"),
  merlin: require("./players/merlin"),
  ET: require("./players/ET"),
  starterbot: require("./players/starterbot"),
  random: require("./players/randombot"),
  theDestiny: require("./players/theDestiny"),
  jakob: require("./players/jakobbot"),
  tRexBot: require("./players/tRexBot"),
  team24: require("./players/team24"),
  dilbert: require("./players/dilbert"),
  // beasty: require("./players/beasty"),
  shootermcgavin: require('./players/shootermcgavin'),
  neinobot: require('./players/neinobot')
  somethingIntimidating: require("./players/somethingIntimidating"),
  superbeam: require("./players/superbeam"),
  team18: require("./players/team18"),
  alwaysAngry: require('./players/alwaysAngry'),
  derricksBotty: require("./players/derricksBotty"),
  ninjaPuppies: require("./players/ninja-puppies"),
  rumba: require("./players/rumba"),
  shootermcgavin: require("./players/shootermcgavin"),
  jadestriker: require("./players/jadestriker"),
};
