module.exports = {
  myTeamBot: require("./players/team19Bot"),
  DanceDanceRevolution: require("./players/DanceDanceRevolution"),
  awesomebot: require("./players/awesomebot"),
  merlin: require("./players/merlin"),
  ET: require("./players/ET"),
  jakob: require("./players/jakobbot"),
  tRexBot: require("./players/tRexBot"),
  team24: require("./players/team24"),
  dilbert: require("./players/dilbert"),
  neinobot: require("./players/neinobot"),
  somethingIntimidating: require("./players/somethingIntimidating"),
  superbeam: require("./players/superbeam"),
  team18: require("./players/team18"),
  alwaysAngry: require("./players/alwaysAngry"),
  derricksBotty: require("./players/derricksBotty"),
  ninjaPuppies: require("./players/ninja-puppies"),
  rumba: require("./players/rumba"),
  jadestriker: require("./players/jadestriker"),
};
