module.exports = {
  starterbot: require("./players/starterbot"),
  random: require("./players/randombot"),
  tRexBot: require("./players/tRexBot"),
  team24: require("./players/team24"),
  dilbert: require("./players/dilbert"),
  // beasty: require("./players/beasty"),
  shootermcgavin: require('./players/shootermcgavin'),
  somethingIntimidating: require("./players/somethingIntimidating"),
  superbeam: require("./players/superbeam"),
  team18: require("./players/team18"),
  alwaysAngry: require('./players/alwaysAngry'),
  derricksBotty: require("./players/derricksBotty"),
  ninjaPuppies: require("./players/ninja-puppies"),
  rumba: require("./players/rumba"),
  shootermcgavin: require("./players/shootermcgavin"),
  jadestriker: require("./players/jadestriker"),
};
